@asp
@api
@javascript

Feature: test ACCESS Support OnDemand Page
  In order to test the OnDemand Page

  Scenario: Unauthenticated user tests the OnDemand Page
    Given I am not logged in
    When I go to "/ondemand"
    Then I should see "Seamless Supercomputing on the Web"
    Then I should see "ACCESS OnDemand"
    Then I should see "Improving the ACCESS Experience"
    Then I should see "Common web-based interfaces integrated with ACCESS services."
    Then I should see "Running OnDemand and don't see your resource listed?"
    Then I should see "Anvil"
    Then I should see an image with alt text "Purdue logo"
    When I click "Anvil"
    Then I should be on "/knowledge/anvil/access/login"
    When I go to "/ondemand"
    Then I should see "Bridges2"
    Then I should see an image with alt text "Bridges2 logo"
    When I click "Bridges2"
    Then I should be on "/resources/bridges-2/user-guide-2-2/#ondemand"
    When I go to "/ondemand"
    Then I should see "DELTA"
    Then I should see an image with alt text "I NCSA Logo"
    When I click "DELTA"
    Then I should be on "/display/DSC/Delta+User+Guide#DeltaUserGuide-DeltaScienceGatewayandOpenOnDemand"
    When I go to "/ondemand"
    Then I should see "Expanse"
    Then I should see an image with alt text "SDSC logo"
    When I click "Expanse"
    Then I should be on "/support/user_guides/expanse.html"
    When I go to "/ondemand"
    Then I should see "Faster"
    Then I should see an image with alt text "Texas A&M University Logo"
    When I click "FASTER"
    Then I should be on "/wiki/SW:Portal"
    When I go to "/ondemand"
    Then I should see "PACE"
    Then I should see an image with alt text "Georgia Tech Logo"
    When I click "PACE"
    Then I should be on "/ood/guide/"
    When I go to "/ondemand"
    Then I should see "Rockfish"
    Then I should see an image with alt text "John Hopkins University"
    When I click "Rockfish"
    Then I should be on "/OpenOnDemand.html"
    When I go to "/ondemand"
    Then I should see "Running OnDemand and don't see your resource listed?"
    Then I should see "For Researchers"
    Then I should see "Use OnDemand on these ACCESS allocated resources"
    Then I should see "Learn more about OnDemand"
    Then I should see an image with alt text "Laptop team"
    Then I should see "ACCESS OnDemand helps computational researchers and students efficiently"
    #TODO Need to test link to Learn More. There are two Learn mre buttons
    Then I should see "Learn More"
    Then I should see "For Resource Providers"
    Then I should see an image with alt text "Team working"
    Then I should see "The ACCESS OnDemand team will be providing OnDemand plugins,"
    #TODO Need to test link to LEarn More
    Then I should see "Learn More"
    Then I should see "Connect with us on Discourse"
    Then I should see "Join the Community"
    Then I should see an image with alt text "Group of people in an office"
    Then I should see "The ACCESS OnDemand project team has a long track record of working with the"
    Then I should see "Join Us"
    When I click "Join Us"
    Then I should be on "https://discourse.openondemand.org/"

