name: cyberteam
recipe: drupal9
env_file:
  - .env
config:
  webroot: web
  database: mysql:5.7
  config:
    php: ./.lando.php.ini
services:
  database:
    api: 3
    portforward: 3300
    healthcheck: mysql --defaults-extra-file=/app/.lando/mysql.cnf --silent --execute "SHOW DATABASES;"
  appserver:
    api: 3
    type: php:8.2
    build_as_root:
      - apt-get update
      - apt-get install libxss1
      - echo "Run additional build commands here. Run lando rebuild after updating this file."
      - apt-get install -y ca-certificates curl gnupg
      - mkdir /etc/apt/keyrings
      - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
      - apt-get update && apt-get install nodejs -y
      - apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth
      - apt install -y xvfb
      - apt update && apt upgrade -y
      - wget -O gh.deb https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb
      - dpkg -i gh.deb
      - rm gh.deb
    run:
      - "cd /app/tests/cypress && npm install && npm_config_no_npx_prompt | npx cypress install"
proxy:
  appserver:
    - '*.cnctci.lndo.site'
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  robo:
    service: appserver
    cmd: /app/vendor/bin/robo
  cypress:
    service: appserver
    cmd: npx cypress
  npm:
    service: appserver
    cmd: /usr/bin/npm
