adding:
  dependencies:
    config:
      - views.view.affinity_group
    module:
      - views
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            36701c15-b1e7-4bf6-88ef-3e6211e4b03b:
              uuid: 36701c15-b1e7-4bf6-88ef-3e6211e4b03b
              region: first
              configuration:
                id: 'views_block:affinity_group-block_8'
                label: ''
                label_display: '0'
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: none
                exposed: {  }
              weight: 7
              additional:
                layout_builder_styles_style:
                  mb_10: mb_10
                  accordion_wrapper: 0
                  bg_light_teal: 0
                  page_title: 0
                  pb_4: 0
                  pe_3: 0
                  pt_4: 0
                  tags: 0
removing: {  }
