adding:
  dependencies:
    config:
      - views.view.affinity_group
    module:
      - views
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            b8d55d75-374b-4733-a506-0d32227ac66a:
              uuid: b8d55d75-374b-4733-a506-0d32227ac66a
              region: first
              configuration:
                id: 'views_block:affinity_group-block_8'
                label: ''
                label_display: '0'
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: none
                exposed: {  }
              weight: 8
              additional:
                layout_builder_styles_style:
                  mb_10: mb_10
                  accordion_wrapper: 0
                  bg_light_teal: 0
                  mb_3: 0
                  mb_5: 0
                  md_teal_box: 0
                  page_title: 0
                  pb_4: 0
                  pe_3: 0
                  pt_4: 0
                  tags: 0
                  __div_h_full: 0
            36701c15-b1e7-4bf6-88ef-3e6211e4b03b:
              uuid: 36701c15-b1e7-4bf6-88ef-3e6211e4b03b
              region: first
              configuration:
                id: 'views_block:affinity_group-block_7'
                label: ''
                label_display: '0'
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: none
                exposed: {  }
              weight: 14
              additional:
                layout_builder_styles_style:
                  mb_10: mb_10
                  accordion_wrapper: 0
                  bg_light_teal: 0
                  page_title: 0
                  pb_4: 0
                  pe_3: 0
                  pt_4: 0
                  tags: 0
removing:
  dependencies:
    config:
      - field.field.node.affinity_group.field_meeting_notes_link
  hidden:
    field_meeting_notes_link: true
