<?php

/**
 * @file
 * ACCESS Theme theme file.
 */

/**
 * Implements hook_preprocess_html().
 */
function accesstheme_preprocess_html(&$vars) {
  // Add the current path as a class attribute on the body element
  $current_path = \Drupal::service('path.current')->getPath();
  $internal = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Assign it to body class 
  $vars['attributes']['class'][] = 'path' . str_replace("/", "-", $internal);
}