name: 'DDEV Cypress Test'
description: 'Run Cypress tests using DDEV'
author: 'necyberteam'

inputs:
  site:
    description: 'Site identifier (e.g. accessmatch, ccmnet)'
    required: true
  directory:
    description: 'Test directory name'
    required: true
  subdirectory:
    description: 'Subdirectory within test directory (optional)'
    required: false
  database:
    description: 'Custom database URL (optional)'
    required: false
  database_branch:
    description: 'Branch to download database artifact from'
    required: false
    default: 'main'
  github_token:
    description: 'GitHub token for authentication'
    required: true
  amp_uid:
    description: 'AMP UID for user authentication'
    required: true
  slack_webhook:
    description: 'Slack webhook URL for notifications (optional)'
    required: false
  slack_bot_token:
    description: 'Slack bot token for file uploads (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download database backup
      if: inputs.database == ''
      uses: dawidd6/action-download-artifact@v6
      with:
        name: amp-daily-backup
        path: backups/
        workflow: backupdb.yml
        branch: ${{ inputs.database_branch }}

    - name: Setup DDEV Base
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      uses: ./.github/actions/ddev-base
      with:
        site: ${{ inputs.site }}
        database: ${{ inputs.database }}
        github_token: ${{ inputs.github_token }}
        amp_uid: ${{ inputs.amp_uid }}

    - name: Download files
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Downloading fresh files from backup..."
        ddev exec gh auth status
        ddev exec vendor/bin/robo gh:pullfiles

    - name: Setup Drupal key for GitHub API
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Create the private keys directory and add GitHub token for Drupal's key module
        # This must run AFTER pullfiles since that wipes the files directory
        mkdir -p web/sites/default/files/private/.keys
        printf '%s' "$GITHUB_TOKEN" > web/sites/default/files/private/.keys/github.key
        chmod 600 web/sites/default/files/private/.keys/github.key
        echo "✅ GitHub key file created ($(wc -c < web/sites/default/files/private/.keys/github.key) bytes)"

    - name: Setup Node.js
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: tests/cypress/package-lock.json

    - name: Install Cypress dependencies
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      run: |
        cd tests/cypress
        npm ci

    - name: Install Cypress system dependencies
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libxtst6 xauth xvfb
        # Install Chrome for Cypress
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify site accessibility
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      env:
        SITE: ${{ inputs.site }}
        TERM: xterm
      run: |
        echo "Checking DDEV status..."
        ddev status
        echo "Testing site accessibility at https://$SITE.ddev.site"
        curl -I "https://$SITE.ddev.site" || echo "Site not accessible"
        echo "DDEV describe output:"
        ddev describe

    - name: Run Cypress tests
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      env:
        SITE: ${{ inputs.site }}
        DIR: ${{ inputs.directory }}
        SUBDIR: ${{ inputs.subdirectory }}
        TERM: xterm
      run: |
        cd tests/cypress
        echo "Testing site URL: https://$SITE.ddev.site"
        if [ -n "$SUBDIR" ] && [ "$SUBDIR" != "" ]; then
          echo "Running tests from: cypress/e2e/$DIR/$SUBDIR/*.js"
          SPEC_PATH="cypress/e2e/$DIR/$SUBDIR/*.js"
        else
          echo "Running tests from: cypress/e2e/$DIR/**/*.js"
          SPEC_PATH="cypress/e2e/$DIR/**/*.js"
        fi
        # Run Cypress tests (let it fail naturally to trigger failure handlers)
        xvfb-run -a npx cypress run --config baseUrl=https://$SITE.ddev.site --spec "$SPEC_PATH"

    - name: Check for screenshots
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Checking for Cypress screenshots..."
        if [ -d "tests/cypress/cypress/screenshots" ]; then
          echo "Screenshots found:"
          ls -la tests/cypress/cypress/screenshots/
        else
          echo "No screenshots directory found"
        fi

    - name: Store date
      shell: bash
      run: |
        echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Store branch
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/pull/* ]]; then
          # For pull requests, use the head branch name
          current_branch=${{ github.head_ref }}
        else
          # For direct branch pushes
          current_branch="${GITHUB_REF#refs/heads/}"
        fi
        echo "CURRENT_BRANCH=$current_branch" >> $GITHUB_ENV

    - name: Add A11y reports to cypress-a11y repo.
      shell: bash
      if: ${{ hashFiles('tests/cypress/cypress-a11y-reports/*.html') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      run: |
        # Use github_token to clone git@github.com:necyberteam/cypress-a11y.git to /tmp/cypress-a11y
        echo "Cloning cypress-a11y repo..."
        git clone https://x-access-token:${{ inputs.github_token }}@github.com/necyberteam/cypress-a11y.git /tmp/cypress-a11y
        mkdir -p /tmp/cypress-a11y/reports/$DATE/$CURRENT_BRANCH/$SUBDIR/${{ github.run_id }}
        cp -r tests/cypress/cypress-a11y-reports/* /tmp/cypress-a11y/reports/$DATE/$CURRENT_BRANCH/$SUBDIR/${{ github.run_id }}/
        cd /tmp/cypress-a11y
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add A11y reports for ${{ inputs.site }}-${{ inputs.directory }} on $DATE (run ${{ github.run_id }} on branch $CURRENT_BRANCH)" || echo "No changes to commit"
        git push origin gh-pages
        echo "A11y reports added to cypress-a11y repo."
      env:
        github_token: ${{ inputs.github_token }}
        SUBDIR: ${{ inputs.subdirectory }}

    - name: Summary
      shell: bash
      if: ${{ hashFiles('tests/cypress/cypress-a11y-reports/*.html') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      run: |
        echo "A11y Report $SUBDIR: https://necyberteam.github.io/cypress-a11y/reports/${{ env.DATE }}/${{ env.CURRENT_BRANCH }}/$SUBDIR/${{ github.run_id }}/summary.html" >> $GITHUB_STEP_SUMMARY
      env:
        SUBDIR: ${{ inputs.subdirectory }}

    - name: Upload A11y reports
      if: ${{ hashFiles('tests/cypress/cypress-a11y-reports/*.html') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      uses: actions/upload-artifact@v4
      with:
        name: cypress-a11y-report-${{ inputs.site }}-${{ inputs.directory }}
        path: tests/cypress/cypress-a11y-reports
        if-no-files-found: ignore

    - name: Upload screenshots on failure
      if: ${{ failure() && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots-${{ inputs.site }}-${{ inputs.directory }}
        path: tests/cypress/cypress/screenshots/
        if-no-files-found: ignore

    - name: Upload screenshots to Slack
      shell: bash
      if: ${{ failure() && inputs.slack_bot_token != '' && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      run: |
        if [ -d "tests/cypress/cypress/screenshots" ]; then
          echo "Uploading screenshots to Slack..."
          cd tests/cypress/cypress/screenshots

          # Channel ID for #cypress-git-notifications
          CHANNEL_ID="C05UU6WN1V4"

          # Find and upload first few screenshot files (limit to avoid spam)
          find . -name "*.png" -type f | head -3 | while read screenshot; do
            if [ -f "$screenshot" ]; then
              FILENAME=$(basename "$screenshot")
              FILESIZE=$(stat -f%z "$screenshot" 2>/dev/null || stat -c%s "$screenshot" 2>/dev/null)
              echo "Uploading $screenshot ($FILESIZE bytes) to Slack..."

              # Step 1: Get upload URL
              upload_url_response=$(curl -s -X POST \
                -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                -H "Content-Type: application/x-www-form-urlencoded" \
                --data-urlencode "filename=$FILENAME" \
                --data-urlencode "length=$FILESIZE" \
                "https://slack.com/api/files.getUploadURLExternal")

              echo "Upload URL response: $upload_url_response"

              UPLOAD_URL=$(echo "$upload_url_response" | jq -r '.upload_url')
              FILE_ID=$(echo "$upload_url_response" | jq -r '.file_id')

              if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" == "null" ]; then
                echo "Failed to get upload URL"
                continue
              fi

              # Step 2: Upload the file to the URL
              curl -s -X POST "$UPLOAD_URL" \
                -F "file=@$screenshot"

              # Step 3: Complete the upload
              complete_response=$(curl -s -X POST \
                -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"files\": [{\"id\": \"$FILE_ID\", \"title\": \"$FILENAME\"}], \"channel_id\": \"$CHANNEL_ID\", \"initial_comment\": \"Cypress test failure: ${{ inputs.site }}-${{ inputs.directory }} - $FILENAME\"}" \
                "https://slack.com/api/files.completeUploadExternal")

              echo "Complete upload response: $complete_response"
            fi
          done
        fi

    - name: Notify Slack on failure
      if: ${{ failure() && inputs.slack_bot_token != '' && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_MESSAGE: 'Cypress tests failed for ${{ inputs.site }}-${{ inputs.directory }}. Screenshots also uploaded above.'
        SLACK_TITLE: "Cypress Test Failure"
        SLACK_CHANNEL: cypress-git-notifications

    - name: Notify Slack on failure (no screenshots)
      if: ${{ failure() && inputs.slack_webhook != '' && !cancelled() && hashFiles('tests/cypress/cypress/screenshots/**/*.png') == '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_MESSAGE: 'Cypress tests failed for ${{ inputs.site }}-${{ inputs.directory }}. No screenshots were generated.'
        SLACK_TITLE: "Cypress Test Failure"
        SLACK_CHANNEL: cypress-git-notifications

    - name: Slack - give link back to action if A11y reports exist
      if: ${{ hashFiles('tests/cypress/cypress-a11y-reports/*.html') != '' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_MESSAGE: '❗️❗️ Cypress A11y reports are here: https://necyberteam.github.io/cypress-a11y/reports/${{ env.DATE }}/${{ env.CURRENT_BRANCH }}/${{ env.SUBDIR }}/${{ github.run_id }}/summary.html The action ran is here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ❗️❗️'
        SLACK_TITLE: "Cypress A11y Reports Available"
        SLACK_CHANNEL: cypress-git-notifications

    - name: Get Drupal logs on failure
      shell: bash
      if: ${{ failure() && !cancelled() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
      run: |
        echo "Attempting to get Drupal logs..."
        ddev drush wd-show --count=10000 || echo "Could not retrieve Drupal logs (Drupal may not be fully set up)"

    - name: Cleanup DDEV
      shell: bash
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      run: ddev delete -O -y

    - name: Merge Group
      shell: bash
      if: ${{ github.event_name == 'merge_group' }}
      run: |
        echo 'Let Merge Queue pass'

branding:
  icon: 'check-circle'
  color: 'green'
