id: not_found
uuid: 2dc110e1-3430-43c8-8e06-a33e223c708c
type: 'page not found'
message: '@uri'
referer: ''
threshold: '50'
window: '1 hour ago'
provider: ban
user_type: '1'
rule_type: 1
langcode: en
status: true
dependencies: {  }
