id: honeypot_urls_4
uuid: 7bec7ce8-dd3a-48d1-802e-aa8122f3e92e
type: 'page not found'
message: /.github/|/.gitlab-ci.yml|/.gitlab-ci/|/.gitlab/|/.gitignore|/.gitattributes|/.git-credentials|/.git-secret|/.gitconfig|/.git-askpass|/.git/config~|/.git/config.bak|/.git-secret/|/private/keys|/private/sendgrid|/private/secret|/private/.env
referer: ''
threshold: '2'
window: '1 hour ago'
provider: ban
user_type: '0'
rule_type: 1
langcode: en
status: true
dependencies: {  }
