id: denied
uuid: 7b7fe09b-7851-42b7-8db8-8a4f7545f29e
type: 'access denied'
message: '@uri'
referer: ''
threshold: '20'
window: '1 hour ago'
provider: ban
user_type: '0'
rule_type: 1
langcode: en
status: true
dependencies: {  }
