id: honeypot_urls_2
uuid: f767e67e-ee74-44c4-933f-27d0f14f4b0f
type: 'page not found'
message: /dropdown.php|/epinyins.php|/ext.php|/install.php|/joomla.xml|/magento_version|/magento_version|/manifest.json|/phpinfo.php|/queues|/readme.html|/server-status|/shell.php|/ssh|/taf.php|/test.php|/web.config|/web.config|/wp-comments-post.php
referer: ''
threshold: '2'
window: '1 hour ago'
provider: ban
user_type: '0'
rule_type: 1
langcode: en
status: true
dependencies: {  }
