id: honeypot_facets
uuid: 3e411f6a-12d7-4be5-b8d8-447fc305b85d
type: facets_honeypot
message: 'Bot box checked'
referer: ''
threshold: '1'
window: '1 hour ago'
provider: ban
user_type: '1'
rule_type: 1
langcode: en
status: true
dependencies: {  }
