id: honeypot_urls_5
uuid: 6a1a0f18-c7bc-489f-a22b-ec14a83cdc3f
type: 'page not found'
message: /root/.git-credentials|/~/.gitconfig|/~/.git-credentials|/vendor/drupal/coder/.git|/static/.git|/app/.git|/wp-config.php|/wp-admin/|/wp-includes/|/xmlrpc.php|/wp-content/plugins/|/wp-content/themes/|/wp-json/wp/|/wp-trackback.php|/wp-signup.php
referer: ''
threshold: '2'
window: '1 hour ago'
provider: ban
user_type: '0'
rule_type: 1
langcode: en
status: true
dependencies: {  }
