<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Yaml;

/**
 * Implements hook_form_alter().
 */
function ood_software_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Alter the node edit form for 'software' content type.
  if ($form_id === 'node_appverse_app_edit_form' || $form_id === 'node_appverse_app_form') {
    $form['field_appverse_github_url']['widget'][0]['uri']['#placeholder'] = 'https://github.com/organization/repo';
    unset($form['field_appverse_github_url']['widget'][0]['uri']['#description']);

    // Add prefix/suffix to make the fieldset ajax-replaceable.
    $form['group_github']['#prefix'] = '<div id="edit-group-github">';
    $form['group_github']['#suffix'] = '</div>';

    $form['group_github']['lookup_button'] = [
      '#type' => 'button',
      '#value' => t('Fetch Repo'),
      '#limit_validation_errors' => array(),
      '#weight' => 12,
      '#attributes' => [
        'class' => [
          'ml-0'
        ],
      ],
      '#ajax' => [
        'callback' => 'ood_software_fetch_github_data',
        'wrapper' => 'edit-group-github',
      ],
    ];

    $form['actions']['submit']['#submit'][] = 'ood_software__edit_submit';
  }
}

/**
 * Ajax call to pull in Github data.
 */
function ood_software_fetch_github_data(array &$form, FormStateInterface $form_state) {
  $gh = \Drupal::service('ood_software.gh');
  $validUrl = $gh->parseUrl($form_state->getValue('field_appverse_github_url')[0]['uri']);
  if ($validUrl) {
    $data = $gh->getData();

    // Set value.
    $form_state->setValue('body', [['value' => $gh->getDescription()]]);
    $form_state->setValue('field_appverse_readme', [['value' => $gh->getReadme()]]);
    $form_state->setValue('title', [['value' => $gh->getRepoName()]]);
    $form_state->setValue('field_appverse_lastupdated', [['value' => $gh->getLastComittedDate()]]);

    // Also update the form element to reflect the change.
    $form['body']['widget'][0]['value']['#value'] = $gh->getDescription();
    $form['field_appverse_readme']['widget'][0]['value']['#value'] = $gh->getReadme();
    $form['title']['widget'][0]['value']['#value'] = $gh->getRepoName();
    $form['field_appverse_lastupdated']['widget'][0]['value']['#value'] = $gh->getLastComittedDate();

  }

  return $form['group_github'];

}

/**
 * Form submit handler for science.
 */
function ood_software__edit_submit($form, FormStateInterface $form_state) {
}
