name: (M) PHPUnit Tests
on:
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      database:
        description: 'Recent database dump to use (leave blank to use artifact)'
      database_branch:
        description: 'Branch to download database artifact from (default: main)'
        default: 'main'
      group:
        description: 'PHPUnit @group filter (default: access_affinitygroup)'
        default: 'access_affinitygroup'

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/ddev-phpunit
        with:
          group: ${{ github.event.inputs.group || 'access_affinitygroup' }}
          database: ${{ github.event.inputs.database }}
          database_branch: ${{ github.event.inputs.database_branch }}
          github_token: ${{ secrets.GH_TOKEN_REPO }}
          amp_uid: ${{ secrets.AMP_UID }}
