name: (A) Pull request - behat
on:
  pull_request:
permissions:
  contents: read
  actions: write
  pull-requests: write
jobs:
  pr:
    name: Actions to run on a pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the value of branch
        id: branch
        run: |
          echo "branch=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
      - name: Set the value of prnum
        id: prnum
        run: |
          echo "prnum=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV
      - name: Run full behat tests
        run: |
          echo '{"database":"", "sites":"$SITE", "prnum":"$PRNUM"}' | gh workflow run behat.yml -R $REPO -r $BRANCH --json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
          PRNUM: ${{ env.prnum }}
          SITE: "cci, asp, champ, coco, usrse, careers, gpc, ky, nect"
          REPO: "${{ github.server_url }}/${{ github.repository }}"
          BRANCH: ${{ env.branch }}
