name: (AM) Security Updates
on:
  workflow_dispatch:
  schedule:
    - cron:  '20 17,18,19,20,21 * * 3'
permissions:
  actions: read
  contents: write
  pull-requests: write
jobs:
  build:
    name: Check for security updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: ./.github/actions/dingorunner
        env:
          runner: bkup
          terminus_api: ${{ secrets.TERMINUS_API }}
          SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_DEPLOY_KEY}}
          site_name: ${{ secrets.TERMINUS_SITE_NAME }}
          env: live

      - id: DDEV
        uses: ./.github/actions/ddev-base
        with:
          site: "accessmatch"
          database: ''
          github_token: ${{ secrets.GH_TOKEN_REPO }}
          amp_uid: ${{ secrets.AMP_UID }}

      - name: Run robo su
        run: |
          vendor/bin/robo su --no-interaction
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
